appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: UETQ3bVKDuzhk7j6MDjHvvv3XPv4XGXrt9Q+X43M14hVQR1P/kCD0vJTr7KCTh2KzFtUIgjt/oYFesQ7b3owtzEjcxnu8aVGsbDZEu29k2HdwAqGFw7vfrzoQA+vuwQ8Hj2zPoqnz/J5oZuU+pf+XmQ6o2dQw66WH0F90nnl5rQZGOTrHNKgR/DmQefkheTS75lUSdTcJrZu8pg8iXPUmyF8tEfYjTfexbaQO3MU0ITMN9yWlL7srJqZuSJmHDxpnUMI//snr+Ua/xGPrsOPHKa9fErjlBw/i+Gf1b1DGkIag83AYeaDSjE9auM+Gsw2CSx2jHpFkXzggUXhF5FrImBI1/JX5/jAWZFrvZqSZlrOAvwuNclEoKzgoWPJAPmjfRgn4TsvGtJzz802W3NPZgrt1j2m7mhb484ToYv13ysqK0ONOZ16jJ6XE8n7ALcZ1W4joFpHPoa3ZCxQKx9HoJp/f2bry0RoJnjj9Avnr483nlH+6F061g40zNxtRay7/d2w0GhX5PTDu7S06cSIgROI6paKxpnXoUhNVERXBK4VBWk0MU1CfQryHAy0ODNo0qRF0wm6wZuHdoZrZAP7+9mVUtoKfbHhhuDqDJiG7vAyeQgj5GH/5OlR77LatlVEuzywJUluUCdcg3frYYr+TsAkqXHGFxJ5HpfKOlfW3Zc=}
